#!/usr/bin/env python3
"""
Generate the BC-ResNet parity fixture from the CONTROLLER's scorer.

The two implementations score the same audio on the same device, so any
divergence between them shows up as a shadow-mode disagreement that looks
like a model problem. This pins them together the way stream_fixture.bin
pins the openWakeWord pipeline to Python's.

It deliberately does NOT need onnxruntime or a model: what has to agree is
the buffering, the peak normalisation, the softmax and the smoothing. The
graph itself is the same file byte-for-byte at both ends, and ORT's own
numerics are its problem, not ours.

Regenerate:
    cd device/internal/wakeword/bcresnet/testdata
    ~/.venv/bin/python gen_fixture.py
"""
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[5] / "controller"))
import em_wake_scorer as ws  # noqa: E402

# Small enough to keep the fixture readable, and NOT a whole number of chunks —
# the real window is 22400, i.e. 17.5 chunks, and an integral test window would
# hide an implementation that assumed otherwise.
WINDOW = 3 * ws.CHUNK_SAMPLES + 640
SPEC = ws.BcresnetSpec(
    window=WINDOW,
    sample_rate=16000,
    labels=("noise", "ohphelia", "unknown"),
    wake_index=1,
    norm_peak=0.8,
    n_mels=40,
    clip_seconds=WINDOW / 16000,
)

# Deterministic across languages: an explicit LCG, not numpy's RNG, so the Go
# side can reproduce the input without shipping the samples.
def lcg(n, seed=12345):
    out = np.empty(n, dtype=np.int16)
    x = seed
    for i in range(n):
        x = (1103515245 * x + 12345) & 0x7FFFFFFF
        out[i] = np.int16((x >> 8) % 20001 - 10000)
    return out


class Recorder:
    """Records each normalised window and returns logits that vary per call,
    so the smoothing is exercised rather than being a constant."""

    def __init__(self):
        self.windows = []

    def __call__(self, x):
        i = len(self.windows)
        self.windows.append(np.array(x[0], copy=True))
        return np.array([[0.5, 1.0 + 0.5 * i, -0.25]], dtype=np.float32)


def main():
    n_chunks = 12
    audio = lcg(n_chunks * ws.CHUNK_SAMPLES)

    rec = Recorder()
    scorer = ws.BcresnetScorer(rec, SPEC, hop_chunks=2, smoothing=3)

    scores = []
    for i in range(n_chunks):
        chunk = audio[i * ws.CHUNK_SAMPLES:(i + 1) * ws.CHUNK_SAMPLES]
        s = scorer.push(chunk)
        scores.append(None if s is None else float(s))

    fixture = {
        "comment": "generated by gen_fixture.py — see the module docstring",
        "window": WINDOW,
        "chunkSamples": ws.CHUNK_SAMPLES,
        "hopChunks": 2,
        "smoothing": 3,
        "normPeak": SPEC.norm_peak,
        "wakeIndex": SPEC.wake_index,
        "labels": list(SPEC.labels),
        "lcgSeed": 12345,
        "chunks": n_chunks,
        # None where the chunk produced no score. The Go side must produce
        # nothing at exactly the same positions: a hop that has drifted by one
        # chunk still scores, and still disagrees with the controller forever.
        "scores": scores,
        # The normalised window at each hop, which is what the model actually
        # sees. Recorded in full because a buffering bug that keeps the wrong
        # 1.4s scores plausibly and is invisible in the final number.
        "windows": [w.tolist() for w in rec.windows],
    }
    out = Path(__file__).with_name("parity_fixture.json")
    out.write_text(json.dumps(fixture))
    print(f"wrote {out} ({out.stat().st_size} bytes), "
          f"{len(rec.windows)} scored windows of {WINDOW} samples")


if __name__ == "__main__":
    main()
