#!/usr/bin/env python3
"""Generate deployed_fixture.json: SPEC §5.1 window preparation and the
deployed graph's logits for deterministic windows.

The preparation below is the SPEC §5.1 text, line for line. The logits come
from the deployed graph (SHA-256 4eb74512…), so the Go ORT test proves the
device session reproduces the shipped weights, and the pure-Go test proves the
preparation.

    /tmp/em-venv/bin/python gen_fixture.py /path/to/bcresnet_audio.onnx /path/to/bcresnet_audio.json
"""
import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import onnxruntime as ort

GRAPH_SHA256 = "4eb745120ea56f5681eddbf788a0c69e1fd406d4694a04a4dba0c1e41d862d3f"
SIDECAR_SHA256 = "25da0c652c562bf0a45a8f34bb46e38788bfc689e31401f33950831a0f2af51f"
WINDOW = 22400
PROBE_STRIDE = 101

# name, seed, modulus, offset, loud_from, loud_modulus, loud_offset.
# Sample i is ((x >> 8) % modulus) - offset from a 31-bit LCG, switching to the
# loud recipe from sample loud_from on (loud_from = WINDOW: never).
RECIPES = [
    ("noise_loud", 12345, 20001, 10000, WINDOW, 0, 0),
    ("noise_full_scale", 777, 65536, 32768, WINDOW, 0, 0),
    ("noise_quiet", 4242, 17, 8, WINDOW, 0, 0),
    ("noise_below_floor", 99, 7, 3, WINDOW, 0, 0),
    ("burst", 2024, 41, 20, 14000, 12001, 6000),
]


def lcg_window(seed, mod, off, loud_from, loud_mod, loud_off):
    out = np.empty(WINDOW, dtype=np.int16)
    x = seed
    for i in range(WINDOW):
        x = (1103515245 * x + 12345) & 0x7FFFFFFF
        if i < loud_from:
            out[i] = (x >> 8) % mod - off
        else:
            out[i] = (x >> 8) % loud_mod - loud_off
    return out


def main(graph, sidecar):
    graph_bytes = Path(graph).read_bytes()
    sidecar_bytes = Path(sidecar).read_bytes()
    assert hashlib.sha256(graph_bytes).hexdigest() == GRAPH_SHA256, "not the deployed graph"
    assert hashlib.sha256(sidecar_bytes).hexdigest() == SIDECAR_SHA256, "not the deployed sidecar"
    spec = json.loads(sidecar_bytes)

    so = ort.SessionOptions()
    so.intra_op_num_threads = 1
    so.execution_mode = ort.ExecutionMode.ORT_SEQUENTIAL
    sess = ort.InferenceSession(graph, so, providers=["CPUExecutionProvider"])

    windows = []
    for name, seed, mod, off, loud_from, loud_mod, loud_off in RECIPES:
        pcm = lcg_window(seed, mod, off, loud_from, loud_mod, loud_off)
        x = pcm.astype(np.float32) / np.float32(32768.0)
        rms = float(np.sqrt(np.mean(x.astype(np.float64) ** 2)))
        entry = {
            "name": name, "seed": seed, "modulus": mod, "offset": off,
            "loud_from": loud_from, "loud_modulus": loud_mod, "loud_offset": loud_off,
            "rms": rms, "scored": rms >= 1e-4,
        }
        if entry["scored"]:
            p = float(np.abs(x).max())
            if p > 1e-4:
                x = x * np.float32(spec["normPeak"] / p)
            logits = sess.run(None, {"audio": x[None, :]})[0][0].astype(np.float64)
            e = np.exp(logits - logits.max())
            entry.update({
                "peak": p,
                "probe": [float(v) for v in x[::PROBE_STRIDE]],
                "sum": float(np.sum(x.astype(np.float64))),
                "sum_sq": float(np.sum(x.astype(np.float64) ** 2)),
                "logits": [float(v) for v in logits],
                "prob": float(e[spec["wakeIndex"]] / e.sum()),
            })
        windows.append(entry)

    fixture = {
        "comment": "generated by gen_fixture.py from the deployed graph",
        "graph_sha256": GRAPH_SHA256,
        "sidecar_sha256": SIDECAR_SHA256,
        "onnxruntime": ort.__version__,
        "probe_stride": PROBE_STRIDE,
        "windows": windows,
    }
    out = Path(__file__).with_name("deployed_fixture.json")
    out.write_text(json.dumps(fixture, indent=1) + "\n")
    for w in windows:
        print(w["name"], w["scored"], w.get("prob"))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
